sudo: required
language: minimal

services:
  - docker

env:
  - LOGSTASH_VERSION=7.7.1
  - DOCKER_IMAGE_NAME=messiahua/logstash

jobs:
  include:
  - stage: logstash config test
    script: '.travis/logstash.sh'
  - stage: build docker image
    script: '.travis/docker.sh'
