sudo: required
language: minimal

services:
  - docker

jobs:
  include:
  - stage: logstash config test
    script: 'docker run -v $PWD/pipeline:/usr/share/logstash/pipeline logstash:7.7.0 --config.test_and_exit'
  - stage: STAGE2
    script: echo "THIS IS STAGE 2"
