apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      component: logstash
  template:
    metadata:
      labels:
        component: logstash
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9198"
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:7.7.1
          livenessProbe:
            httpGet:
              path: /
              port: metrics
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: metrics
            initialDelaySeconds: 30
          ports:
            - containerPort: 5044
              name: filebeat
            - containerPort: 9600
              name: metrics
              protocol: TCP
          volumeMounts:
            - name: pipeline
              mountPath: /usr/share/logstash/pipeline
          envFrom:
            - configMapRef:
                name: logstash-env
          env:
            - name: XPACK_MONITORING_ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: es-credentials
                  key: es_username
            - name: XPACK_MONITORING_ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: es-credentials
                  key: es_password
        - name: logstash-exporter
          image: bonniernews/logstash_exporter:v0.1.2
          command: ["/bin/sh", "-c"]
          args:
            - >-
              sleep 60;
              exec /logstash_exporter
                --logstash.endpoint=http://localhost:9600
                --web.listen-address=:9198
          ports:
            - name: exporter
              containerPort: 9198
              protocol: TCP
      volumes:
        - name: pipeline
          configMap:
            name: logstash-pipeline
