apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: logstash-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: logstash
  template:
    metadata:
      labels:
        component: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:7.6.2
          ports:
            - containerPort: 5044
              name: filebeat
            # - containerPort: 9600
            #   name: logstash
          volumeMounts:
            - name: pipeline
              mountPath: /usr/share/logstash/pipeline
          envFrom:
            - configMapRef:
                name: logstash-config
          env:
            - name: XPACK_MONITORING_ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: es-credentials
                  key: es_username
            - name: XPACK_MONITORING_ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: es-credentials
                  key: es_password
      volumes:
        - name: pipeline
          hostPath:
            path: /Users/udhokale/logstash/logstash_k8s/pipeline
            type: Directory
