apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  type: ClusterIP
  selector:
    component: logstash
  ports:
    - name: beats
      port: 5044
      protocol: TCP
  selector:
    component: logstash
