apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: logstash
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: logstash
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: External
      external:
        metric:
          name: logstash_node_pipeline_events
        target:
          type: AverageValue
          averageValue: 25
