apiVersion: v1
kind: Service
metadata:
  name: logstash-loadbalancer
spec:
  selector:
    component: logstash
  ports:
    # - name: 'logstash'
      # protocol: TCP
      # port: 9600
      # targetPort: 9600
    - name: 'filebeat'
      port: 5044
      targetPort: 5044
  type: LoadBalancer
