version: 1
patchUpdated:
  generators:
  - command: kubectl create configmap logstash-env --from-env-file=../logstash.properties -o yaml --dry-run
  - command: kubectl create configmap logstash-pipeline --from-file=../pipeline/logstash-default.conf -o yaml --dry-run
  patchFile: flux-patch.yaml
