---
# Source: filebeat/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  labels:
    app.kubernetes.io/name: filebeat
    helm.sh/chart: filebeat-4.0.0
    app.kubernetes.io/instance: filebeat
    app.kubernetes.io/managed-by: Helm
---
# Source: filebeat/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: filebeat
  labels:
    app.kubernetes.io/name: filebeat
    helm.sh/chart: filebeat-4.0.0
    app.kubernetes.io/instance: filebeat
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  filebeat.yml: ICAgIGZpbGViZWF0LmNvbmZpZzoKICAgICAgbW9kdWxlczoKICAgICAgICBwYXRoOiAke3BhdGguY29uZmlnfS9tb2R1bGVzLmQvKi55bWwKICAgICAgICByZWxvYWQuZW5hYmxlZDogdHJ1ZQogICAgZmlsZWJlYXQuaW5wdXRzOgogICAgLSBlbmFibGVkOiB0cnVlCiAgICAgIGhvc3Q6IDAuMC4wLjA6ODAKICAgICAgdHlwZTogdGNwCiAgICBodHRwLmVuYWJsZWQ6IGZhbHNlCiAgICBodHRwLnBvcnQ6IDUwNjYKICAgIG91dHB1dC5maWxlOgogICAgICBlbmFibGVkOiBmYWxzZQogICAgICBmaWxlbmFtZTogZmlsZWJlYXQKICAgICAgbnVtYmVyX29mX2ZpbGVzOiA1CiAgICAgIHBhdGg6IC91c3Ivc2hhcmUvZmlsZWJlYXQvZGF0YQogICAgICByb3RhdGVfZXZlcnlfa2I6IDEwMDAwCiAgICBvdXRwdXQubG9nc3Rhc2g6CiAgICAgIGhvc3RzOgogICAgICAtIGxvZ3N0YXNoOjUwNDQ=
---
# Source: filebeat/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat
  labels:
    app.kubernetes.io/name: filebeat
    helm.sh/chart: filebeat-4.0.0
    app.kubernetes.io/instance: filebeat
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  verbs: ["get", "list", "watch"]
---
# Source: filebeat/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat
  labels:
    app.kubernetes.io/name: filebeat
    helm.sh/chart: filebeat-4.0.0
    app.kubernetes.io/instance: filebeat
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: filebeat
subjects:
- kind: ServiceAccount
  name: filebeat
  namespace: default
---
# Source: filebeat/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  labels:
    app.kubernetes.io/name: filebeat
    helm.sh/chart: filebeat-4.0.0
    app.kubernetes.io/instance: filebeat
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: filebeat
      app.kubernetes.io/instance: filebeat
  minReadySeconds: 10
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: filebeat
        app.kubernetes.io/instance: filebeat
      annotations:
        checksum/secret: fc8e8c6a3d9f459d8f67edf6ab9404e2f21e8ba6aa7fc2cc1d5e7bca33a0ddc6
    spec:
      initContainers:
      containers:
      - name: filebeat
        image: "docker.elastic.co/beats/filebeat:7.7.1"
        imagePullPolicy: IfNotPresent
        args:
        - "-e"
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: filebeat-config
          mountPath: /usr/share/filebeat/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: filebeat-config
        secret:
          secretName: filebeat
      - name: data
        hostPath:
          path: /var/lib/filebeat
          type: DirectoryOrCreate
      terminationGracePeriodSeconds: 60
      serviceAccountName: filebeat
