serviceAccounts:
  alertmanager:
    create: false
  nodeExporter:
    create: false
  pushgateway:
    create: false

alertmanager:
  enabled: false

kubeStateMetrics:
  enabled: false

nodeExporter:
  enabled: false

server:
  enabled: true
  name: server

  image:
    repository: prom/prometheus
    tag: v2.19.1

  global:
    scrape_interval: 10s
    scrape_timeout: 10s
    evaluation_interval: 1m

  persistentVolume:
    enabled: false

  replicaCount: 1

pushgateway:
  enabled: false

extraScrapeConfigs:
  # - job_name: 'prometheus-blackbox-exporter'
  #   metrics_path: /probe
  #   params:
  #     module: [http_2xx]
  #   static_configs:
  #     - targets:
  #       - https://example.com
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: prometheus-blackbox-exporter:9115

